# Generated by Django 5.0.14 on 2026-07-23 21:13

import apps.core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rfq_number', models.CharField(default=apps.core.utils.generate_rfq_number, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('submission_deadline', models.DateField()),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='procurement.purchaserequisition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFQLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_of_measure', models.CharField(default='PCS', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('pr_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.purchaserequisitionline')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rfq.rfq')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFQSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_suppliers', to='rfq.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'unique_together': {('rfq', 'supplier')},
            },
        ),
    ]
