# Generated by Django 6.0.7 on 2026-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PO_CREATED', 'PO Created'), ('FINANCIAL_REVIEW', 'Financial Review'), ('FINANCIAL_APPROVED', 'Financial Approved'), ('FINAL_APPROVAL', 'Final Approval'), ('PO_APPROVED', 'PO Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('GOODS_RECEIVED', 'Goods Received')], default='PO_CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
