# Generated by Django 6.0.7 on 2026-07-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreview',
            name='new_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialreview',
            name='previous_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialreview',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
