# Generated by Django 6.0.7 on 2026-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('REQUESTER', 'Requester'), ('BUDGET_HOLDER', 'Budget Holder'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('FINANCIAL_REVIEWER', 'Financial Reviewer'), ('WAREHOUSE_OFFICER', 'Warehouse Officer'), ('ADMIN', 'Administrator'), ('SYSTEM_ADMINISTRATOR', 'System Administrator')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
